# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
              echo "Printing pipeline variables:"
              for var in $(printenv); do
                if [[ $var == *'='* ]]; then
                  name=$(echo $var | cut -d '=' -f 1)
                  value=$(echo $var | cut -d '=' -f 2)
                  # Check if it's a pipeline variable
                  if [[ $name == BUILD_* || $name == SYSTEM_* || $name == AGENT_* ]]; then
                    echo "$name = $value"
                  fi
                fi
              done
  displayName: "Print Pipeline Variables"
